name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: my-website
          git-user: Clement-Fernandes
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages